
  | Name    | Type             | Params | Mode
-----------------------------------------------------
0 | conv1   | Conv2d           | 320    | train
1 | conv2   | Conv2d           | 18.5 K | train
2 | conv3   | Conv2d           | 73.9 K | train
3 | dropout | Dropout          | 0      | train
4 | fc1     | Linear           | 1.3 K  | train
5 | loss_fn | CrossEntropyLoss | 0      | train
-----------------------------------------------------
94.0 K    Trainable params
0         Non-trainable params
94.0 K    Total params
0.376     Total estimated model params size (MB)
6         Modules in train mode
0         Modules in eval mode
/Users/francescocentomo/anaconda3/envs/MLOPS_p1/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:433: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
Epoch 9: 100%|██████████████████████| 187/187 [00:02<00:00, 76.61it/s, v_num=y9ti]
`Trainer.fit` stopped: `max_epochs=10` reached.
Traceback (most recent call last):
  File "/Users/francescocentomo/Desktop/MLOPS/MLOPS_p1/src/mlops_p1/lightning_train.py", line 38, in <module>
    main()
  File "/Users/francescocentomo/Desktop/MLOPS/MLOPS_p1/src/mlops_p1/lightning_train.py", line 34, in main
    trainer.test(model, test_dataloader)
  File "/Users/francescocentomo/anaconda3/envs/MLOPS_p1/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 774, in test
    return call._call_and_handle_interrupt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/francescocentomo/anaconda3/envs/MLOPS_p1/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 49, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/francescocentomo/anaconda3/envs/MLOPS_p1/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 816, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/francescocentomo/anaconda3/envs/MLOPS_p1/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 961, in _run
    _verify_loop_configurations(self)
  File "/Users/francescocentomo/anaconda3/envs/MLOPS_p1/lib/python3.12/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 41, in _verify_loop_configurations
    __verify_eval_loop_configuration(model, "test")
  File "/Users/francescocentomo/anaconda3/envs/MLOPS_p1/lib/python3.12/site-packages/pytorch_lightning/trainer/configuration_validator.py", line 106, in __verify_eval_loop_configuration
    raise MisconfigurationException(f"No `{step_name}()` method defined to run `Trainer.{trainer_method}`.")
lightning_fabric.utilities.exceptions.MisconfigurationException: No `test_step()` method defined to run `Trainer.test`.
